### ISSUE TITLE
Maxline ui bug

### ISSUE THREAD

**Issue by mobres14** [MaxIceFlame/MaxLine-Feedback#1]
so that day at thursday july 6 2023, i just found a maxline bugs at main menu ui, and i try find the solution by extract the game to unity file(sorry i didn't mean that but i'm just trying to find the bug), and i found the main menu ui then i see this

![image](https://github.com/MaxIceFlame/MaxLine-Feedback/assets/107705449/9b2d96e4-e528-4b94-9517-6e66ec89c2f2)

maybe you should try to fix that ok ?

Thank you <3 :3
-Mobres

**Comment by mobres14** [comment]
here, i show the problem, the mainmenu and skinmenu UI

https://cdn.discordapp.com/attachments/899656818505170945/1152648221198393495/2023-09-17_01-48-46.mp4

i can't post video in here, cuz video is too big by github

**Comment by MaxIceFlame** [comment]
we have fixed it, please wait for the next update. thanks for your feedback
