### ISSUE TITLE
沙滩关卡的白屏错误及部分水面泛白问题（极高画质高质量水面质量）

### ISSUE THREAD

**Issue by shangecgfhcghvcgvg** [MaxIceFlame/MaxLine-Feedback#2]
因为未知原因导致无法上传视频文件，所以只能在描述：在一冠和二冠之间的转场，如果在转场时线的位置不在原先预定位置会使游戏白屏，不会出现死亡界面；在线转场到水下之前的水面泛白。

**Comment by MaxIceFlame** [comment]
转场问题已修复，水面泛白为水面shader相关问题，暂时无能力修复
